usuarios:
  property: Usuarios Profile Dev Update
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/db_examenes
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      dll-auto: update
    show-sql: true
    generate-dll: true
